### ISSUE TITLE
Foundry website login change broke authentication helper utility

### ISSUE THREAD

**Issue by worldofgeese** [felddy/foundryvtt-docker#868]
### Bug description

I restarted my container today to find authentication failing with `Unable to authenticate: check your credentials`. In the official Foundry Discord, I was informed that Foundry made changes to the way website authentication works. 

### Steps to reproduce

Restart your container.

### Expected behavior

Container should automatically login.

### Container metadata

```shell
I'm using a Helm chart that consumes this container. It's the latest 11.315. I can confirm it's not an issue with the chart as another user using just the bare Docker container reproduced the error.
```

### Relevant log output

```console
Entrypoint | 2024-01-05 14:45:37 | [info] Starting felddy/foundryvtt container v11.315.0
Entrypoint | 2024-01-05 14:45:37 | [info] No Foundry Virtual Tabletop installation detected.
Entrypoint | 2024-01-05 14:45:37 | [info] Using FOUNDRY_USERNAME and FOUNDRY_PASSWORD to authenticate.
Authenticate | 2024-01-05 14:45:37 | [info] Requesting CSRF tokens from https://foundryvtt.com
Authenticate | 2024-01-05 14:45:38 | [info] Logging in as: fulminatingloris
Authenticate | 2024-01-05 14:45:39 | [error] Unable to log in as fulminatingloris, verify your credentials...
Authenticate | 2024-01-05 14:45:39 | [error] Unable to authenticate: Unable to log in as fulminatingloris, verify your credentials...
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by flexstrongo** [comment]
I'm having this issue as well with the standard docker-compose.  For now, you can get around it by providing a S3 temp url from foundry if you need the install files, or if your docker container already has them, you can comment out the login/pw sections of the compose and it will use the local files already in place.

**Comment by felddy** [comment]
Confirmed by continuous integration that this is now broken: 
- https://github.com/felddy/foundryvtt-docker/actions/runs/7420513190/job/20202134729#step:14:85

I knew this day would come.   I'm actually surprised it continued to work this many years. 

 I'll make this a priority to get this repaired ASAP.   
 
As mentioned  by @flexstrongo, the workaround is to [use the S3 temp URL](https://github.com/felddy/foundryvtt-docker/issues/868#issuecomment-1878805479).

**Comment by felddy** [comment]
The fix has been merged.  And is being currently being published: 
- https://github.com/felddy/foundryvtt-docker/actions/runs/7424429341

As soon as the workflow completes it will be available for install using the `:edge` tag `felddy/foundryvtt:edge`.


After I merge in a few outstanding PRs from dependabot I'll publish a release for `v11.315.1`.  

Thank you all for the report and help.

**Comment by ruipin** [comment]
Is there any plan to update older Foundry containers? I still have a world running FVTT 0.8.9 and the `0.8.9` tag is unfortunately broken as well. Due to a bunch of modules in use, updating it to a more recent FVTT version would take a lot of work that I would prefer not to have to do 😅 

EDIT: Seems that commenting out the login information is enough of a workaround given I already had the 0.8.9 files in the cache. I guess it's not a problem them, nevermind.

**Comment by felddy** [comment]
`0.8.9` whoa... Yeah it's probably just enough to disable credentials for now.  

You can probably use the latest version of the container and set `FOUNDRY_VERSION` to `0.8.9` but I haven't tested that.

**Comment by felddy** [comment]
@ruipin I just tested running container `11.315.1` with `FOUNDRY_VERSION` `0.8.9`  and it doesn't work.  The root of the problem is the change from semver in the `0.x.x` line of releases to the new scheme they use.  So the logic that calculates the release URL fails.  Best to stick with disabling the credentials for now.

**Comment by CyberKiller40** [comment]
Could this be backported to version 10? I'm still using that for some running games and older modules.

**Comment by felddy** [comment]
> Could this be backported to version 10? I'm still using that for some running games and older modules.

@CyberKiller40,
I don't think a back port is required.  FoundryVTT Version `10.303`  should work with the current container image `11.315.1`.

To do this set the `FOUNDRY_VERSION` environment variable to `10.303` and your image tag to a current version .  e.g., `felddy/foundryvtt:11`

I was able to successfully able to start the server and vend a world in my test environment.  

> [!CAUTION]
> Since this isn't a tested configuration I would make a backup if your `data` directory before attempting this with a real world.  That said I expect the risk to be low that any badness ensues.  

You will see some warning in the logs about the version mismatch:

```console
foundry-1  | Entrypoint | 2024-02-12 11:33:22 | [warn] FOUNDRY_VERSION has been manually set and does not match the container's version.
foundry-1  | Entrypoint | 2024-02-12 11:33:22 | [warn] Expected 11.315 but found 10.303
foundry-1  | Entrypoint | 2024-02-12 11:33:22 | [warn] The container may not function properly with this version mismatch.
```

This is similar to the guidance for running future versions of Foundry:
- https://github.com/felddy/foundryvtt-docker/discussions/796

Please let me know if this solution works well for you, or if you have any issues.

**Comment by CyberKiller40** [comment]
Oh, cool, I'll check if it works.

**Comment by CyberKiller40** [comment]
Confirm, setting a FOUNDRY_VERSION env with image ver 11, works correctly.
